fractals1: fractals1.c
	gcc fractals1.c -lGL -lGLU -lglut -lm

fractals2: fractals2.c
	gcc fractals2.c -lGL -lGLU -lglut -lm -fopenmp

fractals3: fractals3.c
	gcc fractals3.c -lGL -lGLU -lglut -lm -fopenmp

run:
	./a.out

clean:
	rm a.out
